staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia
      url: https://ethereum-sepolia-rpc.publicnode.com
  account:
    workflow-owner-address: ""
  workflows:
    - workflow: workflow/verify-poc/workflow.yaml
