import { useReadContract } from 'wagmi'
import { BOUNTY_HUB_ADDRESS, BOUNTY_HUB_V2_ABI } from '../config'

/**
 * Hook to read a project's public key from BountyHub V2
 * @param projectId The project ID to query
 * @returns Object containing publicKey, isLoading, and error
 */
export function useProjectPublicKey(projectId: bigint | null) {
  const effectiveProjectId = projectId ?? 0n

  const { data, isLoading, error } = useReadContract({
    address: BOUNTY_HUB_ADDRESS,
    abi: BOUNTY_HUB_V2_ABI,
    functionName: 'projects',
    args: [effectiveProjectId],
    query: {
      enabled: projectId !== undefined && projectId !== null
    }
  })

  // useReadContract returns the entire Project struct as a tuple
  // projectPublicKey is the 12th field (index 11)
  const projectPublicKey = data ? (data as readonly unknown[])[11] as `0x${string}` : null

  // Return null if public key is empty (not yet generated by workflow)
  const publicKey = projectPublicKey && projectPublicKey.length > 0
    ? projectPublicKey
    : null

  return {
    publicKey,
    isLoading,
    error: error as Error | null
  }
}
