[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@oasisprotocol/sapphire-contracts/=lib/sapphire-paratime/contracts/",
    "oasisprotocol-sapphire-foundry/=lib/sapphire-paratime/integrations/foundry/lib/oasisprotocol-sapphire-foundry/"
]
ffi = true
via_ir = true
optimizer = true
optimizer_runs = 1000
additional_compiler_profiles = [
    {name = "sapphire-paris", evm_version = "paris"},
    {name = "bountyhub-compact", optimizer_runs = 1}
]
compilation_restrictions = [
    {paths = "script/DeployOasisPoCStore.s.sol", evm_version = "paris"},
    {paths = "script/DeployBountyHubV4.s.sol", optimizer_runs = 1}
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
sapphire_testnet = "${SAPPHIRE_TESTNET_RPC_URL}"
